# Generated by Django 4.2 on 2023-07-13 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mememodel_dislikes_alter_mememodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='cdislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='clikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
